### ISSUE TITLE
Chrome extension build example

### ISSUE THREAD

**Issue by jcalfee** [stoodkev/hive-keychain#104]
Would you please point me in the right direction?  I would like to build the hive-keychain chrome extension..

**Comment by stoodkev** [comment]
Hi! We re refactoring the extension to use React but as of now there is nothing to build.
You just need to clone from github, go to your browser extension page, activate dev mode and select "Load unpacked" (might vary depending on browser).

**Comment by jcalfee** [comment]
Thank you

**Comment by jcalfee** [comment]
I'm trying to get to a build that I can verify as much of the code as possible.  Some "vendor" libraries are not clear by looking at the start of the file.

Do all of these libraries in "vendor" have builds on npm?  What package and version are you using?

crypto-js
decode
hive
md5
ssc

**Comment by stoodkev** [comment]
decode is created via browserify (see the decode_wrapper folder), the rest have builds on npm but I'm guessing its not up to date by now. 
The current code is a mess, it started as a simple project and grew a lot, that's why we are refactoring. If you want to contribute, I would strongly suggest that you wait a couple of months until we're done (see the `refactor` branch that uses React)

**Comment by jcalfee** [comment]
Thanks .. I just wanted to verify the code before I put my private key in..
