### ISSUE TITLE
'requestBroadcast error' on Keychain.

### ISSUE THREAD

**Issue by deniskariuki** [stoodkev/hive-keychain#32]
I started getting this error when I updated to the latest version v1.8.2.5. Tried rolling back and the same error is still there. I cannot post or claim rewards.

![image](https://user-images.githubusercontent.com/30696312/79051691-483b1380-7c3a-11ea-87e0-e9a32a5ff03d.png)

**Comment by VIM-Arcange** [comment]
@deniskariuki the image link looks broken. Can you update it?

**Comment by deniskariuki** [comment]
Not sure why because it loads up for me. Let me re-upload it here.

![79051691-483b1380-7c3a-11ea-87e0-e9a32a5ff03d](https://user-images.githubusercontent.com/30696312/79062460-55d8b380-7ca3-11ea-96a2-3135fdefef60.png)

**Comment by VIM-Arcange** [comment]
This is not a hive-keychain generated message, but one displayed by the app you use, probably because it cannot link to the hive_keychain extension.
Please check with the app developer.
If you are the developer, check the value of window.hive_keychain in your script before calling requestBroadcast()

```
if(window.hive_keychain) {
    // Hive Keychain extension installed...
} else {
    // Hive Keychain extension not installed...
}
```

**Comment by deniskariuki** [comment]
It has resolved. It seems PeakD took a bit of time to recognize the new extension.

**Comment by stoodkev** [comment]
After updating the extension you need to reload pages or it won't work.
